### ISSUE TITLE
Analogs not read from c3d (ezc3d issue)

### ISSUE THREAD

**Issue by zybermonk** [kineticstoolkit/kineticstoolkit#219]
**Describe the bug**
I have some c3d files recorded from a Mocap system. ktk library does not read the analogs from these c3d files from default. However, When I open the files in a biomechanics viewer (mokka) analogs are present. And when I export the exact file from mokka, now ktk reads the analogs. 

**Expected behavior**
how to read the analogs directly from the c3d without exporting from the software. 

![image](https://github.com/kineticstoolkit/kineticstoolkit/assets/97350314/caf96174-d5fb-4ba8-ac18-9c91c0e062f0)

In the screenshot, the first output, ktk shows no analogs, when just opened and exported back from a software like mokka, it shows analogs as displayed in the second output.

Looking forward for any help.
Thanks

**Comment by zybermonk** [comment]
Hi, Thanks for the support.
Just sent the files to your work email.

Regards.

**Comment by felixchenier** [comment]
Hi @zybermonk 

Thanks for sending me the files. As you mention, in the original files, the analog signals are not loaded. I inspected the whole structure provided by ezc3d and I could not find these signals anywhere. Therefore it's not possible to solve it on KTK's side. I suggest you to submit the same bug on ezc3d's repository https://github.com/pyomeca/ezc3d/issues

and to link both issues by copy-pasting this link in the new issue:
https://github.com/kineticstoolkit/kineticstoolkit/issues/219

just so that I can follow it and know what to do with your issue here.

**Comment by pariterre** [comment]
Hi @felixchenier 

I'll take it from here on https://github.com/pyomeca/ezc3d/issues/307

**Comment by pariterre** [comment]
See https://github.com/pyomeca/ezc3d/pull/309
